[package]
name = "blockies-cli"
version = "0.1.1"
authors = ["debris <marek.kotewicz@gmail.com>"]
edition = "2018"

[dependencies]
blockies = { path = "../" }
clap = { version = "2", features = ["yaml"] }

[[bin]]
name = "blockies"
path = "src/main.rs"
doc = false
